[tool.briefcase]
project_name = "Class"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/class"
license = "BSD license"
author = 'Jane Developer'
author_email = "jane@example.com"

[tool.briefcase.app.class]
formal_name = "Class"
description = "My first application"
icon = "src/class/resources/class"
sources = ['src/class']
requires = []


[tool.briefcase.app.class.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.class.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.class.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.class.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.class.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
