name: Upload Python Package

on:
  release:
    types: published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          ref: main
      - name: Set build variables
        run: |
          export TAG=${{ github.event.release.tag_name }}
          echo "TAG=${TAG}"
          echo "VERSION=${TAG#v}"
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Download release artefacts
        run: |
          pip download --dest dist --no-deps briefcase --no-binary :all: briefcase==${{ env.VERSION }}
          pip download --dest dist --no-deps briefcase --only-binary :all: briefcase==${{ env.VERSION }}
      - name: Check files
        run: |
          ls -1 dist
      - name: Publish release to production PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_PASSWORD }}
