name: Upload Python Package

on:
  release:
    types: published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install twine
    - name: Download source tarball
      uses: actions/download-artifact@v3
      with:
        name: source
        path: dist
    - name: Download wheel
      uses: actions/download-artifact@v3
      with:
        name: wheel
        path: dist
    - name: Publish release
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        echo Twine username is ${{ env.TWINE_USERNAME }} (or $TWINE_USERNAME )
        echo Files:
        ls -1 dist
        # python -m twine upload dist/*
