name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          ref: main
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install build check_manifest setuptools_scm twine
      - name: Check manifest
        run: |
          check-manifest -v
      - name: Build release artefacts
        run: |
          python -m build --sdist --wheel dist/ .
      - name: Check release artefacts
        run: |
          python -m twine check dist/*
      - name: Upload release artefacts
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
